export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUEST_STUDENTS_PENDING = 'REQUEST_STUDENTS_PENDING'
export const REQUEST_STUDENTS_SUCCESS = 'REQUEST_STUDENTS_SUCCESS'
export const REQUEST_STUDENTS_FAIL = 'REQUEST_STUDENTS_FAIL'